apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: recommendation-service-ns

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml
  - hpa.yaml

patches:
  - path: scale-down-overlay.yaml